# GitHub Pages Configuration for SimulateAI Domain Redirect
# This file configures GitHub Pages to serve the redirect page

# Basic Jekyll configuration
title: "SimulateAI - Redirecting to simulateai.io"
description: "SimulateAI has moved to simulateai.io - AI Ethics Education Through Interactive Simulations"
url: "https://simulateai.io"
baseurl: ""

# GitHub Pages settings
source: "."
destination: "_site"

# Exclude files that shouldn't be published to GitHub Pages
exclude:
  - node_modules/
  - package*.json
  - .gitignore
  - README.md
  - src/
  - dist/
  - build/
  - .firebase/
  - firebase.json
  - .firebaserc
  - vite.config.js
  - rollup.config.js
  - webpack.config.js
  - tsconfig.json
  - .eslintrc*
  - .prettierrc*
  - "*.md"
  - "*.json"
  - "*.js"
  - "*.ts"
  - "*.config.*"
  - .github/
  - .vscode/

# Include only essential files for redirect
include:
  - github-pages-redirect.html

# Redirect settings (if using Jekyll redirect plugin)
plugins:
  - jekyll-redirect-from

# Custom redirect rules (alternative approach)
redirect_from:
  - /index.html
  - /

# SEO settings
lang: en-US
author: SimulateAI Team

# Social media
social:
  name: SimulateAI
  links:
    - https://simulateai.io

# GitHub Pages specific settings
github:
  repository_name: SimulateAI
  owner_name: mindbomber

# Disable Jekyll blog features we don't need
paginate: 1
show_excerpts: false
future: false
unpublished: false

# Theme (using minimal theme for faster loading)
theme: minima

# Markdown settings
markdown: kramdown
highlighter: rouge

# Sass/SCSS settings
sass:
  style: compressed

# Security settings
safe: true
incremental: false
lsi: false

# Custom variables for the redirect
custom:
  new_domain: "https://simulateai.io"
  old_domain: "https://mindbomber.github.io/SimulateAI"
  redirect_delay: 0
