/**
 * Magic Number Constants for SimulateAI
 * Generated by Magic Number Extractor
 * 
 * This file contains extracted magic numbers converted to named constants
 * for better code maintainability and readability.
 */

// DIMENSION Constants
const HEIGHT_80 = 80;

// Z_INDEX Constants
const Z_INDEX_MAXIMUM = 10001;
const Z_INDEX_MAXIMUM = 10002;
const Z_INDEX_DROPDOWN = 1000;
const Z_INDEX_MAXIMUM = 10000;

// TIMING Constants
const DELAY_MS = 5000;
const DELAY_MS = 1000;
const THROTTLE_MS = 100;

export {
  // Add your exported constants here
  // Example: THROTTLE_MS, Z_INDEX_MODAL, MOBILE_BREAKPOINT
};
